apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
  namespace: lab
spec:
  replicas: 1
  serviceName: pgadmin-headless
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin-secrets
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secrets
              key: PGADMIN_DEFAULT_PASSWORD
        volumeMounts:
        - name: pgadmin-storage
          mountPath: /var/lib/pgadmin/data
    
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

  volumeClaimTemplates:
    - metadata:
        name: pgadmin-storage
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 128Mi